config/routes.rb
Rails.application.routes.draw do
  get '/signup', to: 'users#new'
  resources :users, only: [:create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  resources :memos
  root 'memos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :memos, dependent: :destroy

  #渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Dngine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにハッシュしたトークンをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがハッシュしたトークンと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー#{@user.name}を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー#{@user.name}を更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @user == current_user
      redirect_to admin_user_url, alert: 'このユーザーは削除できません'
    else
      @user.destroy
      redirect_to admin_users_url, notice: "ユーザー#{@user.name}を削除しました"
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
    end

    def require_admin
      redirect_to root_url unless current_user.admin?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private
    def login_required
      redirect_to login_url unless current_user
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  def index
    @memos = current_user.memos.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = current_user.memos.new(memo_params)
    if @memo.save
      redirect_to memo_path(@memo), notice: "#{@memo.title}を作成しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      redirect_to memo_path(@memo), notice: "#{@memo.title}を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @memo.destroy!
    redirect_to memos_url, alert: "#{@memo.title}を削除しました"
  end

  private
    def set_memo
      @memo = current_user.memos.find(params[:id])
    end

    def memo_params
      params.require(:memo).permit(:title, :content, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  before_action :forbidden_loggedin_user, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      log_in user
      session_params[:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url, notice: 'ログインしました'
    else
      flash.now.alert = 'メールアドレスまたはパスワードが間違っています'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path, notice: 'ログアウトしました'
  end

  private
    def forbidden_loggedin_user
      redirect_to memos_path if logged_in?
    end

    def session_params
      params.require(:session).permit(:email, :password, :remember_me)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to memos_url, notice: "#{@user.name}さんようこそ！"
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    #@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #永続セッションを破棄する
  def forget(user)
    user.forget #モデルで定義したメソッド、DBのハッシュしたトークンを削除
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  #ユーザーのセッションの永続化
  def remember(user)
    user.remember #モデルで定義したメソッド、トークンをハッシュしてDBに保存
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.erb
<% if user.errors.any? %>
  <ul class='alert aler-warning'>
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, @user], local: true do |f| %>
  <div class='form-group'>
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-check mt-3 mb-3">
    <%= f.label :admin, class: 'form-check-label' do  %>
      <%= f.check_box :admin, class: 'form-check-input' %> | 管理者権限
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class='mt-5'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>

<div class="nav justify-content-end mb-3">
  <%= link_to 'ユーザー詳細', admin_user_path(@user), class: 'btn btn-secondary' %>
</div>

<%= render partial: 'form', locals: {user: @user} %>

app/views/admin/users/index.html.erb
<h1>ユーザーの一覧</h1>

<div class='nav justify-content-end mb-5'>
  <%= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary' %>
</div>

<div class="mb-5">
  <table class='table table-hover'>
    <thead class='thead-default'>
      <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th><%= User.human_attribute_name(:admin) %></th>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, admin_user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.admin? ? 'あり' : 'なし' %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td>
            <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3' %>
            <%= link_to '削除', [:admin, user], method: :delete, data: {confirm: "ユーザー#{user.name}を削除します。よろしいですか？"},
                  class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class='mb-3'>
  <%= paginate @users %>
</div>

app/views/admin/users/new.html.erb
<h1>ユーザーの登録</h1>

<div class='nav justify-content-end mb-3'>
  <%= link_to 'ユーザーの一覧', admin_users_path, class: 'btn btn-secondary' %>
</div>

<%= render partial: 'form', locals: {user: @user} %>

app/views/admin/users/show.html.erb
<h1>ユーザーの詳細</h1>

<div class='nav justify-content-end mb-3'>
  <%= link_to '一覧', admin_users_path, class: 'btn btn-secondary' %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= User.human_attribute_name(:id) %></th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:name) %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:email) %></th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:admin) %></th>
      <td><%= @user.admin? ? 'あり' : 'なし' %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:created_at) %></th>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name(:updated_at) %></th>
      <td><%= @user.updated_at %></td>
    </tr>
  </tbody>
</table>

<div class="nav justify-content-end">
  <%= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary mr-3' %>
  <%= link_to '削除 ', [:admin, @user], method: :delete, data: {confirm: "ユーザー#{@user.name}を削除します。よろしいですか"},
        class: 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">MemoApp</a>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to 'ユーザーの一覧', admin_users_path, class: 'nav-link'%></li>
          <% end %>
          <li class='nav-item'><%= link_to 'メモ一覧', memos_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li class='nav-item'><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class='nav-item'><%= link_to 'サインアップ', signup_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </nav>

    <div class="container">
      <div class="mt-3">
        <% if flash.notice.present? %>
          <div class='alert alert-success'>
            <%= flash.notice %>
          </div>
        <% end %>
        <% if flash.alert.present? %>
          <div class='alert alert-danger'>
            <%= flash.alert %>
          </div>
        <% end %>
      </div>

      <%= yield %>
    </div>

    <div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/memos/_form.erb
<% if memo.errors.any? %>
  <ul class='alert alert-warning'>
    <% memo.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: memo, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>編集</h1>

<div class="nav justify-content-end mb-3">
  <%= link_to '一覧', memos_path, class: 'btn btn-secondary' %>
</div>

<%= render partial: 'form', locals: {memo: @memo} %>

app/views/memos/index.html.erb
<h1>メモ一覧</h1>

<div class='nav justify-content-end mb-5'>
  <%= link_to '新規登録', new_memo_path, class: 'btn btn-primary' %>
</div>

<div class='mb-5'>
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= Memo.human_attribute_name(:title) %></th>
        <th><%= Memo.human_attribute_name(:content) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @memos.each do |memo| %>
        <tr>
          <td><%= memo.title %></td>
          <td><%= memo.content %></td>
          <td>
            <%= link_to '詳細', memo, class: 'btn btn-secondary mr-3' %>
            <%= link_to '編集', edit_memo_path(memo), class: 'btn btn-primary mr-3' %>
            <%= link_to '削除', memo, method: :delete,
                  data: {confirm: "メモ#{memo.title}を削除します。よろしいですか？"}, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class='mb-3'>
  <%= paginate @memos %>
</div>

app/views/memos/new.html.erb
<h1>新規登録</h1>

<div class="nav justify-content-end mb-3">
  <%= link_to '一覧', memos_path, class: 'btn btn-secondary' %>
</div>

<%= render partial: 'form', locals: {memo: @memo} %>

app/views/memos/show.html.erb
<h1>詳細</h1>

<div class="nav justify-content-end mb-3">
  <%= link_to '一覧', memos_path, class: 'btn btn-secondary' %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= Memo.human_attribute_name(:id) %></th>
      <td><%= @memo.id %></td>
    </tr>
    <tr>
      <th><%= Memo.human_attribute_name(:title) %></th>
      <td><%= @memo.title %></td>
    </tr>
    <tr>
      <th><%= Memo.human_attribute_name(:content) %></th>
      <td><%= @memo.content %></td>
    </tr>
    <tr>
      <th><%= Memo.human_attribute_name(:image) %></th>
      <td><%= image_tag @memo.image.variant(resize:'800x800').processed if @memo.image.attached? %></td>
    </tr>
    <tr>
      <th><%= Memo.human_attribute_name(:created_at) %></th>
      <td><%= @memo.created_at %></td>
    </tr>
    <tr>
      <th><%= Memo.human_attribute_name(:updated_at) %></th>
      <td><%= @memo.updated_at %></td>
    </tr>
  </tbody>
</table>
<div class="nav justify-content-end mt-3">
  <%= link_to '編集', edit_memo_path(@memo), class: 'btn btn-primary' %>
</div>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<% if @user.errors.any? %>
  <ul class='alert alert-warning'>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="mt-5">
    <%= f.submit '登録', class: 'btn btn-primary' %>
  </div>
<% end %>